apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: 3scale-task
spec:
  # workspaces:
  #   - name: source
  #   - name: gradle-cache
  # params:
  #   - name: goals
  #     description: gradle goals to run
  #     type: array
  #     default:
  #       - "clean"
  #       - "build"
  #   - name: application_dir
  #     description: application directory
  #     type: string
  #     default: .
  steps:
    - name: 3scale-export
#      image: registry.redhat.io/3scale-amp2/toolbox-rhel7:1.5.0
      image: quay.io/redhat/3scale-toolbox
   #   workingdir: $(workspaces.source.path)/$(params.application_dir)
      script: |
        #!/usr/bin/env bash
        3scale remote add -k 3scale-instance https://c52764ac4cf73158758a319371289a6a79f0fbc425c7d14f3ad1580cb3afe0f7@3scale-admin.apps.ocp4.example.com
        3scale service list -k 3scale-instance
        3scale product export -k -f /tmp/api.yaml 3scale-instance hello_world_product
        cat /tmp/api.yaml
      # securitycontext:
      #   runasuser: 08c00b1d8143f2894418866dcef7e5af0486e6b397be7ecc64b36fb3c0fbbca11Untitled Document 1
