apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: 3scale-task
spec:
  # workspaces:
  #   - name: source
  #   - name: gradle-cache
  # params:
  #   - name: goals
  #     description: gradle goals to run
  #     type: array
  #     default:
  #       - "clean"
  #       - "build"
  #   - name: application_dir
  #     description: application directory
  #     type: string
  #     default: .
  steps:
    - name: 3scale-export
#      image: registry.redhat.io/3scale-amp2/toolbox-rhel7:1.5.0
      image: quay.io/redhat/3scale-toolbox
   #   workingdir: $(workspaces.source.path)/$(params.application_dir)
      script: |
        #!/usr/bin/env bash
        3scale remote add 3scale-src "http://8c00b1d8143f2894418866dcef7e5af0486e6b397be7ecc64b36fb3c0fbbca11@3scale-admin.apps.ocp4.example.com"
        3scale service list 3scale-src
        3scale product export -f /tmp/api.yaml 3scale-src test_api
        cat /tmp/api.yaml
      # securitycontext:
      #   runasuser: 08c00b1d8143f2894418866dcef7e5af0486e6b397be7ecc64b36fb3c0fbbca11Untitled Document 1
