apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: apply-application
spec:
  inputs:
    params:
    - name: destination
      description: The name of the 3scale_toolbox remote
    - name: secretName
      description: Name of the secret containing the 3scale_toolbox remotes list
    - name: serviceSystemName
      description: The system_name of the service
    - name: planSystemName
      description: The system_name of the application plan
    - name: name
      description: The name of the application to create
    - name: description
      description: The description of the application to create
    - name: userKey
      description: The API Key of the Application
    - name: account
      description: The Application's account ID
  steps:
  - name: apply-application
    image: nmasse/3scale-toolbox:master
    env:
    - name: "HOME"
      value: "/config"
    command:
    - 3scale
    args:
    - application
    - apply
    - ${inputs.params.destination}
    - ${inputs.params.userKey}
    - --service=${inputs.params.serviceSystemName}
    - --plan=${inputs.params.planSystemName}
    - --name=${inputs.params.name}
    - --description=${inputs.params.description}
    - --account=${inputs.params.account}
    volumeMounts:
    - name: "toolbox-config"
      mountPath: /config
  volumes:
  - name: toolbox-config
    secret:
      secretName: ${inputs.params.secretName}