apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: 3scale-copy-product
spec:
  params:
    - name: 3scale_source_secret_name
      description: 3scale source secret
      type: string
      default: "3scale-source-secret"
    - name: 3scale_destination_secret_name
      description: 3scale destination secret
      type: string
      default: "3scale-destinantion-secret"
    - name: 3scale_product_name
      description: 3scale product name
      type: string
      default: "hello_world_product"
  steps:
    - name: 3scale-export
      image: quay.io/redhat/3scale-toolbox
        - name: 3SCALE_SOURCE_URL
          valueFrom:
            secretKeyRef:
              name: $(params.3scale_source_secret_name)
              key: URL
        - name: 3SCALE_DESTINATION_URL
          valueFrom:
            secretKeyRef:
              name: $(params.3scale_destination_secret_name)
              key: URL
      script: |
        #!/usr/bin/env bash
        3scale remote add -k 3scale-source $3SCALE_SOURCE_URL
        3scale remote add -k 3scale-destination $3SCALE_DESTINATION_URL
        3scale service list -k 3scale-instance
        3scale product export -k -f /tmp/product.yaml 3scale-source $(params.3scale_product_name)
        3scale product import -k -f /tmp/product.yaml 3scale-destination
